
/*DROP TABLE T_AM_SCN_BAIRRO;
DROP TABLE T_AM_SCN_CIDADE;
DROP TABLE T_AM_SCN_CLIENTE;
DROP TABLE T_AM_SCN_CONSUMO;
DROP TABLE T_AM_SCN_ESTADO;
DROP TABLE T_AM_SCN_FUNCIONARIO;
DROP TABLE T_AM_SCN_HIST_PRECO;
DROP TABLE T_AM_SCN_HIST_VALOR;
DROP TABLE T_AM_SCN_HOSPEDAGEM;
DROP TABLE T_AM_SCN_LOGRADOURO;
DROP TABLE T_AM_SCN_PAG_CHEQUE;
DROP TABLE T_AM_SCN_PAGAMENTO;
DROP TABLE T_AM_SCN_PAGCARTAO;
DROP TABLE T_AM_SCN_PESSOA;
DROP TABLE T_AM_SCN_PESSOA_ENDE;
DROP TABLE T_AM_SCN_PESSOA_FONE;
DROP TABLE T_AM_SCN_PRODUTO_SERVICO;
DROP TABLE T_AM_SCN_QUARTO;
DROP TABLE T_AM_SCN_REL_CHEQUE;
DROP TABLE T_AM_SCN_RESERVA;
DROP TABLE T_AM_SCN_RESERVA_QUARTO;
DROP TABLE T_AM_SCN_TELEFONE;
DROP TABLE T_AM_SCN_TIPO_FONE;
DROP TABLE T_AM_SCN_TIPO_FORMAPAG;
DROP TABLE T_AM_SCN_TIPO_LOG;
DROP TABLE T_AM_SCN_TIPO_QUARTO;*/


CREATE TABLE T_AM_SCN_CLIENTE(
    CD_CLIENTE NUMBER(5) NOT NULL ,
    NR_CPF NUMBER (11) NOT NULL ,
    NR_RG CHAR (10) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL ,
    NR_QUARTO_PREFERIDO NUMBER (4) ,
    DS_EMAIL VARCHAR2 (60) NOT NULL ,
    DS_SENHA VARCHAR2 (20) NOT NULL
);

CREATE TABLE T_AM_SCN_RESERVA(
    CD_RESERVA  NUMBER (8) NOT NULL ,
    CD_CLIENTE  NUMBER (5) NOT NULL ,
    CD_FUNCIONARIO  NUMBER (5) NOT NULL ,
    DT_SOLICITACAO  DATE NOT NULL ,
    DT_INICIO_RESERVA DATE NOT NULL ,
    DT_FINAL_RESERVA  DATE NOT NULL ,
    QT_ADULTO NUMBER (1) NOT NULL ,
    QT_CRIANCA NUMBER (1) NOT NULL ,
    ST_RESERVA NUMBER (1) NOT NULL
);

CREATE TABLE T_AM_SCN_RESERVA_QUARTO(
    CD_RESERVA  NUMBER (8) NOT NULL ,
    NR_QUARTO   NUMBER (4) NOT NULL ,
    QT_PESSOA_QUARTO NUMBER (1) NOT NULL ,
    DS_OBSERVACAO VARCHAR2 (128)
);

CREATE TABLE T_AM_SCN_HOSPEDAGEM(
    CD_HOSPEDAGEM  NUMBER (8) NOT NULL ,
    NR_QUARTO  NUMBER (4) NOT NULL ,
    CD_RESERVA NUMBER (8) NOT NULL ,
    CD_CLIENTE NUMBER (5) NOT NULL ,
    CD_FUNCIONARIO NUMBER (5) NOT NULL ,
    DT_ENTRADA DATE NOT NULL ,
    DT_SAIDA   DATE ,
    VC_PERC_DESCONTO NUMBER (5,2) NOT NULL
);




CREATE TABLE T_AM_SCN_QUARTO(
    NR_QUARTO NUMBER (4) NOT NULL ,
    CD_TIPO_QUARTO NUMBER (2) NOT NULL ,
    NR_ANDAR NUMBER (2) NOT NULL ,
    NR_CAPACIDADE NUMBER (1) NOT NULL
);


CREATE TABLE T_AM_SCN_PAGAMENTO(
    CD_HOSPEDAGEM  NUMBER (8) NOT NULL ,
    CD_TIPO_FORMAPAG NUMBER (1) NOT NULL ,
    DT_PAGAMENTO  DATE NOT NULL ,
    VL_PAGAMENTO  NUMBER (8,2) NOT NULL
);

CREATE TABLE T_AM_SCN_HIST_VALOR(
    CD_HISTORICO  NUMBER (6) NOT NULL ,
    CD_TIPO_QUARTO  NUMBER (2) NOT NULL ,
    DT_VALIDADE DATE NOT NULL ,
    VL_PRECO_QUARTO NUMBER (4) NOT NULL
);

CREATE TABLE T_AM_SCN_FUNCIONARIO(
    CD_FUNCIONARIO NUMBER (5) NOT NULL ,
    DT_ADMISSAO  DATE NOT NULL ,
    DS_CARGO  NUMBER (1) NOT NULL
);

CREATE TABLE T_AM_SCN_PAGCARTAO(
    CD_PAGTO_CARTAO NUMBER (6) NOT NULL ,
    CD_HOSPEDAGEM  NUMBER (8) NOT NULL ,
    QT_PARCELA   NUMBER (1) NOT NULL
);


CREATE TABLE T_AM_SCN_PAG_CHEQUE(
    CD_PAGTO_CHEQUE NUMBER (6) NOT NULL ,
    CD_HOSPEDAGEM   NUMBER (8) NOT NULL ,
    NR_BANCO        NUMBER (4) NOT NULL
);

CREATE TABLE T_AM_SCN_LOGRADOURO(
    NR_CEP NUMBER (8) NOT NULL ,
    CD_BAIRRO NUMBER (5) NOT NULL ,
    DS_DESCRICAO VARCHAR2 (60) NOT NULL ,
    CD_TIPO_LOGRADOURO NUMBER (2) NOT NULL
);

CREATE TABLE T_AM_SCN_TELEFONE(
    CD_FONE NUMBER (8) NOT NULL ,
    CD_TIPO_FONE NUMBER (2) NOT NULL ,
    NR_DD NUMBER (3) NOT NULL ,
    NR_TELEFONE  NUMBER (9) NOT NULL
);
CREATE TABLE T_AM_SCN_BAIRRO(
    CD_BAIRRO NUMBER (5) NOT NULL ,
    CD_CIDADE NUMBER (5) NOT NULL ,
    NM_BAIRRO VARCHAR2 (30) NOT NULL
);

CREATE TABLE T_AM_SCN_CIDADE(
    CD_CIDADE NUMBER (5) NOT NULL ,
    CD_ESTADO NUMBER (2) NOT NULL ,
    NM_CIDADE VARCHAR2 (30) NOT NULL
);

CREATE TABLE T_AM_SCN_ESTADO(
    CD_ESTADO NUMBER (2) NOT NULL ,
    NM_ESTADO VARCHAR2 (20) NOT NULL ,
    SG_ESTADO CHAR (2 CHAR) NOT NULL
);

CREATE TABLE T_AM_SCN_PESSOA(
    CD_PESSOA NUMBER (5) NOT NULL ,
    NM_PESSOA VARCHAR2 (60) NOT NULL
);

CREATE TABLE T_AM_SCN_TIPO_QUARTO(
    CD_TIPO_QUARTO NUMBER (2) NOT NULL ,
    DS_TIPO_QUARTO VARCHAR2 (25) NOT NULL ,
    DS_OBSERVACAO  VARCHAR2 (128)
);

CREATE TABLE T_AM_SCN_TIPO_FORMAPAG(
    CD_TIPO_FORMAPAG NUMBER (1) NOT NULL ,
    DS_FORMAPAG      VARCHAR2 (40) NOT NULL
);


CREATE TABLE T_AM_SCN_PESSOA_ENDE(
    CD_PESSOA_ENDE NUMBER (8) NOT NULL ,
    NR_CEP         NUMBER (8) NOT NULL ,
    CD_PESSOA      NUMBER (5) NOT NULL ,
    NR_LOGRADOURO  NUMBER (8) NOT NULL ,
    DS_COMPLEMENTO VARCHAR2 (30)
);


CREATE TABLE T_AM_SCN_TIPO_LOG(
    CD_TIPO_LOGRADOURO NUMBER (2) NOT NULL ,
    DS_TIPO_LOGRADOURO VARCHAR2 (30) NOT NULL
);


CREATE TABLE T_AM_SCN_TIPO_FONE(
    CD_TIPO_FONE NUMBER (2) NOT NULL ,
    DS_TIPO_FONE VARCHAR2 (20) NOT NULL
);

CREATE TABLE T_AM_SCN_HIST_PRECO(
    CD_HIST_PRECO   NUMBER (8) NOT NULL ,
    CD_TIPO_SERVICO NUMBER (5) NOT NULL ,
    DT_VALIDADE     DATE NOT NULL ,
    VL_PRECO        NUMBER (6,2) NOT NULL
);

CREATE TABLE T_AM_SCN_CONSUMO(
    CD_CONSUMO      NUMBER (8) NOT NULL ,
    CD_HOSPEDAGEM   NUMBER (8) NOT NULL ,
    CD_TIPO_SERVICO NUMBER (8) NOT NULL ,
    CD_FUNCIONARIO  NUMBER (5) NOT NULL ,
    DT_CONSUMO      DATE NOT NULL ,
    QT_CONSUMO      NUMBER (3) NOT NULL
);

CREATE TABLE T_AM_SCN_PRODUTO_SERVICO(
    CD_TIPO_SERVICO NUMBER (5) NOT NULL ,
    DS_SERVICO      VARCHAR2 (40 CHAR) ,
    NR_TIPO         NUMBER (1) NOT NULL
);

CREATE TABLE T_AM_SCN_REL_CHEQUE(
    CD_PAGTO_CHEQUE NUMBER (6) NOT NULL ,
    CD_HOSPEDAGEM   NUMBER (8) NOT NULL ,
    NR_CHEQUE       NUMBER (5) NOT NULL ,
    VL_PARCELA      NUMBER (8,2) NOT NULL
);

CREATE TABLE T_AM_SCN_PESSOA_FONE(
    CD_PESSOA NUMBER (5) NOT NULL ,
    CD_FONE   NUMBER (8) NOT NULL ,
    NR_RAMAL  NUMBER (4)
);

ALTER TABLE T_AM_SCN_CLIENTE
ADD CONSTRAINT PK_AM_SCN_CLIENTE PRIMARY KEY (CD_CLIENTE);
ALTER TABLE T_AM_SCN_CLIENTE
ADD CONSTRAINT UN_SCN_CLIENTE_RG UNIQUE (NR_RG);
ALTER TABLE T_AM_SCN_CLIENTE
ADD CONSTRAINT UN_SCN_CLIENTE_CPF UNIQUE (NR_CPF);
ALTER TABLE T_AM_SCN_CLIENTE
ADD CONSTRAINT UN_SCN_CLIENTE_EMAIL UNIQUE (DS_EMAIL);
ALTER TABLE T_AM_SCN_RESERVA
ADD CONSTRAINT CK_AM_SCN_RESERVA CHECK (ST_RESERVA IN (1,2,3)) ;
ALTER TABLE T_AM_SCN_RESERVA
ADD CONSTRAINT CK_AM_SCN_RESERVA_DATA CHECK (DT_FINAL_RESERVA >= DT_INICIO_RESERVA);
ALTER TABLE T_AM_SCN_RESERVA
ADD CONSTRAINT PK_AM_SCN_RESERVA PRIMARY KEY(CD_RESERVA);
ALTER TABLE T_AM_SCN_RESERVA_QUARTO
ADD CONSTRAINT PK_AM_SCN_RESERVA_QUARTO PRIMARY KEY (CD_RESERVA, NR_QUARTO);
ALTER TABLE T_AM_SCN_HOSPEDAGEM
ADD CONSTRAINT CK_AM_SCN_HOSPEDAGEM_DATA CHECK (DT_SAIDA >= DT_ENTRADA);
ALTER TABLE T_AM_SCN_HOSPEDAGEM
ADD CONSTRAINT PK_AM_SCN_HOSPEDAGEM PRIMARY KEY (CD_HOSPEDAGEM);
ALTER TABLE T_AM_SCN_QUARTO
ADD CONSTRAINT PK_AM_SCN_QUARTO PRIMARY KEY (NR_QUARTO) ;
ALTER TABLE T_AM_SCN_PAGAMENTO
ADD CONSTRAINT PK_AM_SCN_PAGAMENTO PRIMARY KEY (CD_HOSPEDAGEM) ;
ALTER TABLE T_AM_SCN_HIST_VALOR
ADD CONSTRAINT PK_AM_SCN_HIST_VALOR PRIMARY KEY (CD_HISTORICO, CD_TIPO_QUARTO);
ALTER TABLE T_AM_SCN_FUNCIONARIO ADD CONSTRAINT PK_AM_SCN_FUNCIONARIO PRIMARY KEY(CD_FUNCIONARIO);
ALTER TABLE T_AM_SCN_PAGCARTAO
ADD CONSTRAINT PK_AM_SCN_PAGCARTAO PRIMARY KEY (CD_PAGTO_CARTAO, CD_HOSPEDAGEM);
ALTER TABLE T_AM_SCN_PAGCARTAO
ADD CONSTRAINT CK_AM_SCN_PAGCARTAO_PARC CHECK (QT_PARCELA > 0) ;
ALTER TABLE T_AM_SCN_PAG_CHEQUE
ADD CONSTRAINT PK_AM_SCN_PAG_CHEQUE PRIMARY KEY (CD_PAGTO_CHEQUE, CD_HOSPEDAGEM);
ALTER TABLE T_AM_SCN_LOGRADOURO
ADD CONSTRAINT PK_AM_SCN_LOGRADOURO PRIMARY KEY (NR_CEP) ;
ALTER TABLE T_AM_SCN_TELEFONE
ADD CONSTRAINT PK_AM_SCN_TELEFONE PRIMARY KEY (CD_FONE) ;
ALTER TABLE T_AM_SCN_BAIRRO
ADD CONSTRAINT PK_AM_SCN_BAIRRO PRIMARY KEY (CD_BAIRRO);
ALTER TABLE T_AM_SCN_CIDADE
ADD CONSTRAINT PK_AM_SCN_CIDADE PRIMARY KEY (CD_CIDADE) ;
ALTER TABLE T_AM_SCN_ESTADO
ADD CONSTRAINT PK_AM_SCN_ESTADO PRIMARY KEY (CD_ESTADO);
ALTER TABLE T_AM_SCN_ESTADO
ADD CONSTRAINT UN_AM_SCN_ESTADO UNIQUE (NM_ESTADO , SG_ESTADO);
ALTER TABLE T_AM_SCN_PESSOA
ADD CONSTRAINT PK_AM_SCN_PESSOA PRIMARY KEY(CD_PESSOA);
ALTER TABLE T_AM_SCN_TIPO_QUARTO
ADD CONSTRAINT PK_AM_SCN_TIPO_QUARTO PRIMARY KEY (CD_TIPO_QUARTO);
ALTER TABLE T_AM_SCN_TIPO_FORMAPAG
ADD CONSTRAINT PK_AM_SCN_TIPO_FORMAPAG PRIMARY KEY (CD_TIPO_FORMAPAG);
ALTER TABLE T_AM_SCN_TIPO_FORMAPAG
ADD CONSTRAINT UN_AM_SCN_TIPO_FORMAPAG UNIQUE (DS_FORMAPAG);
ALTER TABLE T_AM_SCN_PESSOA_ENDE
ADD CONSTRAINT PK_AM_SCN_PESSOA_ENDE PRIMARY KEY (CD_PESSOA_ENDE, NR_CEP) ;
ALTER TABLE T_AM_SCN_TIPO_LOG
ADD CONSTRAINT PK_AM_SCN_TIPO_LOG PRIMARY KEY (CD_TIPO_LOGRADOURO) ;
ALTER TABLE T_AM_SCN_TIPO_LOG
ADD CONSTRAINT UN_AM_SCN_TIPO_LOG UNIQUE (DS_TIPO_LOGRADOURO) ;
ALTER TABLE T_AM_SCN_TIPO_FONE
ADD CONSTRAINT PK_AM_SCN_FONE PRIMARY KEY (CD_TIPO_FONE) ;
ALTER TABLE T_AM_SCN_TIPO_FONE
ADD CONSTRAINT UN_AM_SCN_TIPO_FONE UNIQUE (DS_TIPO_FONE) ;
ALTER TABLE T_AM_SCN_HIST_PRECO
ADD CONSTRAINT PK_AM_SCN_HIST_PRECO PRIMARY KEY (CD_HIST_PRECO, CD_TIPO_SERVICO);
ALTER TABLE T_AM_SCN_CONSUMO
ADD CONSTRAINT PK_AM_SCN_CONSUMO PRIMARY KEY (CD_CONSUMO, CD_HOSPEDAGEM) ;
ALTER TABLE T_AM_SCN_CONSUMO
ADD CONSTRAINT CK_AM_SCN_CONSUMO CHECK (QT_CONSUMO > 0) ;
ALTER TABLE T_AM_SCN_PRODUTO_SERVICO
ADD CONSTRAINT PK_AM_SCN_PRODUTO_SERVICO PRIMARY KEY (CD_TIPO_SERVICO) ;
ALTER TABLE T_AM_SCN_PRODUTO_SERVICO
ADD CONSTRAINT CK_AM_SCN_PRODUTO_SERVICO CHECK(NR_TIPO IN (1,2)) ;
ALTER TABLE T_AM_SCN_PRODUTO_SERVICO
ADD CONSTRAINT UN_AM_SCN_PROD_SERV_DESC UNIQUE(DS_SERVICO) ;
ALTER TABLE T_AM_SCN_REL_CHEQUE
ADD CONSTRAINT PK_AM_SCN_REL_CHEQUE PRIMARY KEY (CD_PAGTO_CHEQUE, CD_HOSPEDAGEM);
ALTER TABLE T_AM_SCN_PESSOA_FONE
ADD CONSTRAINT PK_AM_SCN_PESSOA_FONE PRIMARY KEY (CD_PESSOA, CD_FONE);
ALTER TABLE T_AM_SCN_BAIRRO
ADD CONSTRAINT FK_AM_SCN_BAIRRO_CIDADE FOREIGN KEY (CD_CIDADE) REFERENCES T_AM_SCN_CIDADE (CD_CIDADE);
ALTER TABLE T_AM_SCN_CLIENTE
ADD CONSTRAINT FK_AM_SCN_CLIENTE_PESSOA FOREIGN KEY (CD_CLIENTE) REFERENCES T_AM_SCN_PESSOA(CD_PESSOA);
ALTER TABLE T_AM_SCN_CIDADE
ADD CONSTRAINT FK_AM_SCN_CIDADE_ESTADO FOREIGN KEY (CD_ESTADO) REFERENCES T_AM_SCN_ESTADO (CD_ESTADO) ;
ALTER TABLE T_AM_SCN_FUNCIONARIO
ADD CONSTRAINT FK_AM_SCN_FUNC_PESSOA FOREIGN KEY (CD_FUNCIONARIO) REFERENCES T_AM_SCN_PESSOA (CD_PESSOA);
ALTER TABLE T_AM_SCN_CONSUMO
ADD CONSTRAINT FK_AM_SCN_CONSUMO_FUNCIONARIO FOREIGN KEY (CD_FUNCIONARIO) REFERENCES T_AM_SCN_FUNCIONARIO (CD_FUNCIONARIO);
ALTER TABLE T_AM_SCN_CONSUMO
ADD CONSTRAINT FK_AM_SCN_CONSUMO_PROD_SERV FOREIGN KEY (CD_TIPO_SERVICO) REFERENCES T_AM_SCN_PRODUTO_SERVICO (CD_TIPO_SERVICO);
ALTER TABLE T_AM_SCN_CONSUMO
ADD CONSTRAINT FK_AM_SCN_CONSUMO_HOSPEDAGEM FOREIGN KEY (CD_HOSPEDAGEM) REFERENCES T_AM_SCN_HOSPEDAGEM (CD_HOSPEDAGEM);
ALTER TABLE T_AM_SCN_HOSPEDAGEM
ADD CONSTRAINT FK_AM_SCN_HOSPEDAGEM_FUNC FOREIGN KEY (CD_FUNCIONARIO) REFERENCES T_AM_SCN_FUNCIONARIO (CD_FUNCIONARIO) ;
ALTER TABLE T_AM_SCN_HOSPEDAGEM
ADD CONSTRAINT FK_AM_SCN_HOSPEDAGEM_CLIENTE FOREIGN KEY (CD_CLIENTE) REFERENCES T_AM_SCN_CLIENTE (CD_CLIENTE);
ALTER TABLE T_AM_SCN_HOSPEDAGEM
ADD CONSTRAINT FK_AM_SCN_HOSP_RESERVAQTO FOREIGN KEY (CD_RESERVA, NR_QUARTO) REFERENCES T_AM_SCN_RESERVA_QUARTO (CD_RESERVA,NR_QUARTO);
ALTER TABLE T_AM_SCN_HIST_PRECO
ADD CONSTRAINT FK_AM_SCN_PROD_SERV FOREIGN KEY (CD_TIPO_SERVICO) REFERENCES T_AM_SCN_PRODUTO_SERVICO (CD_TIPO_SERVICO) ;
ALTER TABLE T_AM_SCN_HIST_VALOR
ADD CONSTRAINT FK_AM_SCN_HISTVALOR_TIPOQUARTO FOREIGN KEY (CD_TIPO_QUARTO) REFERENCES T_AM_SCN_TIPO_QUARTO (CD_TIPO_QUARTO);
ALTER TABLE T_AM_SCN_LOGRADOURO
ADD CONSTRAINT FK_AM_SCN_LOGRADOURO_BAIRRO FOREIGN KEY (CD_BAIRRO) REFERENCES T_AM_SCN_BAIRRO (CD_BAIRRO) ;
ALTER TABLE T_AM_SCN_LOGRADOURO
ADD CONSTRAINT FK_AM_SCN_LOGRADOURO_TIPO_LOG FOREIGN KEY (CD_TIPO_LOGRADOURO) REFERENCES T_AM_SCN_TIPO_LOG (CD_TIPO_LOGRADOURO) ;
ALTER TABLE T_AM_SCN_PAGAMENTO
ADD CONSTRAINT FK_AM_SCN_PAGTO_HOSPEDAGEM FOREIGN KEY (CD_HOSPEDAGEM) REFERENCES T_AM_SCN_HOSPEDAGEM (CD_HOSPEDAGEM) ;
ALTER TABLE T_AM_SCN_PAGAMENTO
ADD CONSTRAINT FK_AM_SCN_PAGTO_TIPO_FORMAPAG FOREIGN KEY (CD_TIPO_FORMAPAG) REFERENCES T_AM_SCN_TIPO_FORMAPAG (CD_TIPO_FORMAPAG);
ALTER TABLE T_AM_SCN_PAGCARTAO
ADD CONSTRAINT FK_AM_SCN_PAGCARTAO_PAGTO FOREIGN KEY (CD_HOSPEDAGEM) REFERENCES T_AM_SCN_PAGAMENTO (CD_HOSPEDAGEM);
ALTER TABLE T_AM_SCN_PAG_CHEQUE
ADD CONSTRAINT FK_AM_SCN_PAG_CHEQUE_PAGTO FOREIGN KEY (CD_HOSPEDAGEM) REFERENCES T_AM_SCN_PAGAMENTO (CD_HOSPEDAGEM);
ALTER TABLE T_AM_SCN_PESSOA_ENDE
ADD CONSTRAINT FK_AM_SCN_PESSOA_ENDE_LOG FOREIGN KEY (NR_CEP) REFERENCES T_AM_SCN_LOGRADOURO (NR_CEP);
ALTER TABLE T_AM_SCN_PESSOA_ENDE
ADD CONSTRAINT FK_AM_SCN_PESSOA_ENDE_PESSOA FOREIGN KEY (CD_PESSOA) REFERENCES T_AM_SCN_PESSOA (CD_PESSOA);
ALTER TABLE T_AM_SCN_QUARTO
ADD CONSTRAINT FK_AM_SCN_QUARTO_TIPOQUARTO FOREIGN KEY (CD_TIPO_QUARTO) REFERENCES T_AM_SCN_TIPO_QUARTO (CD_TIPO_QUARTO) ;
ALTER TABLE T_AM_SCN_PESSOA_FONE
ADD CONSTRAINT FK_AM_SCN_PESSOA_FONE_FONE FOREIGN KEY (CD_FONE) REFERENCES T_AM_SCN_TELEFONE (CD_FONE);
ALTER TABLE T_AM_SCN_PESSOA_FONE
ADD CONSTRAINT FK_AM_SCN_PESSOA_FONE_PESSOA FOREIGN KEY (CD_PESSOA) REFERENCES T_AM_SCN_PESSOA (CD_PESSOA);
ALTER TABLE T_AM_SCN_REL_CHEQUE
ADD CONSTRAINT FK_AM_SCN_RELCHEQUE_PAGCHEQUE FOREIGN KEY (CD_PAGTO_CHEQUE, CD_HOSPEDAGEM) REFERENCES T_AM_SCN_PAG_CHEQUE(CD_PAGTO_CHEQUE, CD_HOSPEDAGEM) ;
ALTER TABLE T_AM_SCN_RESERVA
ADD CONSTRAINT FK_AM_SCN_RESERVA_CLIENTE FOREIGN KEY (CD_CLIENTE)REFERENCES T_AM_SCN_CLIENTE(CD_CLIENTE);
ALTER TABLE T_AM_SCN_RESERVA
ADD CONSTRAINT FK_AM_SCN_RESERVA_FUNCIONARIO FOREIGN KEY(CD_FUNCIONARIO) REFERENCES T_AM_SCN_FUNCIONARIO (CD_FUNCIONARIO);
ALTER TABLE T_AM_SCN_RESERVA_QUARTO
ADD CONSTRAINT FK_AM_SCN_RESERVAQTO_RESERVA FOREIGN KEY(CD_RESERVA)REFERENCES T_AM_SCN_RESERVA(CD_RESERVA);
ALTER TABLE T_AM_SCN_RESERVA_QUARTO
ADD CONSTRAINT FK_AM_SCN_RESERVAQUARTO_QUARTO FOREIGN KEY (NR_QUARTO)REFERENCES T_AM_SCN_QUARTO(NR_QUARTO);
ALTER TABLE T_AM_SCN_TELEFONE
ADD CONSTRAINT FK_AM_SCN_FONE_TIPO_FONE FOREIGN KEY (CD_TIPO_FONE) REFERENCES T_AM_SCN_TIPO_FONE (CD_TIPO_FONE) ;
ADD CONSTRAINT FK_AM_SCN_HOSPEDAGEM
