-- QUESTÃO 1 --

SELECT R.CD_RESERVA,P.NM_PESSOA,R.DT_INICIO_RESERVA, R.DT_FINAL_RESERVA, R.QT_ADULTO, R.QT_CRIANCA, R.ST_RESERVA
FROM T_AM_SCN_RESERVA R
JOIN T_AM_SCN_PESSOA P ON P.CD_PESSOA = R.CD_CLIENTE
WHERE R.DT_INICIO_RESERVA >= '01/09/15' AND R.DT_FINAL_RESERVA <= '05/10/15';

-- QUESTÃO 2 **FAZER TIPO QUARTO-- 

SELECT H.CD_HOSPEDAGEM, H.CD_RESERVA, P.NM_PESSOA, H.NR_QUARTO, H.DT_ENTRADA, H.DT_SAIDA
FROM T_AM_SCN_HOSPEDAGEM H
JOIN T_AM_SCN_PESSOA P ON P.CD_PESSOA = H.CD_FUNCIONARIO
WHERE H.DT_ENTRADA >= '01/09/15' AND H.DT_SAIDA <= '31/10/15';

-- QUESTÃO 3 --

SELECT H.CD_HOSPEDAGEM, R.CD_RESERVA , P.NM_PESSOA AS "HOSPEDE", H.NR_QUARTO, TQ.DS_TIPO_QUARTO, HV.VL_PRECO_QUARTO, H.DT_ENTRADA
FROM T_AM_SCN_HOSPEDAGEM H
JOIN T_AM_SCN_RESERVA R ON R.CD_RESERVA = H.CD_RESERVA
JOIN T_AM_SCN_QUARTO Q ON Q.NR_QUARTO = H.NR_QUARTO
JOIN T_AM_SCN_PESSOA P ON P.CD_PESSOA = H.CD_CLIENTE
JOIN T_AM_SCN_TIPO_QUARTO TQ ON TQ.CD_TIPO_QUARTO = Q.CD_TIPO_QUARTO
JOIN T_AM_SCN_HIST_VALOR HV ON Q.CD_TIPO_QUARTO = HV.CD_TIPO_QUARTO
WHERE H.DT_ENTRADA >= '01/09/15' AND H.DT_SAIDA <= '05/10/15' AND HV.DT_VALIDADE >= '01/09/15' AND HV.DT_VALIDADE <= '30/09/15';


-- QUESTAO 4 --

SELECT H.CD_HOSPEDAGEM, R.CD_RESERVA, H.NR_QUARTO, C.QT_CONSUMO, PS.DS_SERVICO, C.DT_CONSUMO, HP.VL_PRECO, C.QT_CONSUMO * HP.VL_PRECO AS "TOTAL"
FROM T_AM_SCN_HOSPEDAGEM H
JOIN T_AM_SCN_RESERVA R ON R.CD_RESERVA = H.CD_RESERVA 
JOIN T_AM_SCN_CONSUMO C ON C.CD_HOSPEDAGEM = H.CD_HOSPEDAGEM
JOIN T_AM_SCN_PRODUTO_SERVICO PS ON PS.CD_TIPO_SERVICO = C.CD_TIPO_SERVICO
JOIN T_AM_SCN_HIST_PRECO HP ON HP.CD_HIST_PRECO= PS.CD_TIPO_SERVICO
WHERE C.DT_CONSUMO = '16/06/15';

-- QUESTAO 5 --
SELECT C.CD_HOSPEDAGEM, H.NR_QUARTO, SUM(C.QT_CONSUMO*HP.VL_PRECO)
FROM T_AM_SCN_HOSPEDAGEM H
JOIN T_AM_SCN_CONSUMO C ON C.CD_HOSPEDAGEM = H.CD_HOSPEDAGEM
JOIN T_AM_SCN_QUARTO Q ON Q.NR_QUARTO = H.NR_QUARTO
JOIN T_AM_SCN_PRODUTO_SERVICO PS ON PS.CD_TIPO_SERVICO = C.CD_TIPO_SERVICO
JOIN T_AM_SCN_HIST_PRECO HP ON HP.CD_HIST_PRECO = PS.CD_TIPO_SERVICO
WHERE C.DT_CONSUMO = '21/06/15'
GROUP BY C.CD_HOSPEDAGEM, H.NR_QUARTO;

-- QUESTAO 6 (FALTA O RANKING ZZ) --
SELECT PS.DS_SERVICO, VARIANCE(HP.VL_PRECO) ,MIN(HP.VL_PRECO) ,MAX(HP.VL_PRECO)
FROM T_AM_SCN_HIST_PRECO HP
JOIN T_AM_SCN_PRODUTO_SERVICO PS ON PS.CD_TIPO_SERVICO = HP.CD_TIPO_SERVICO group by PS.DS_SERVICO
ORDER BY HP.VL_PRECO DESC;

-- QUESTAO 7 --
SELECT P.CD_PESSOA, P.NM_PESSOA AS "FUNCIONÁRIO", SUM(HP.VL_PRECO) AS "TOTAL_VENDA"
FROM T_AM_SCN_CONSUMO C
JOIN T_AM_SCN_PESSOA P ON P.CD_PESSOA = C.CD_FUNCIONARIO
JOIN T_AM_SCN_HIST_PRECO HP ON HP.CD_TIPO_SERVICO = C.CD_TIPO_SERVICO 
GROUP BY P.CD_PESSOA, P.NM_PESSOA;

-- QUESTAO 8 --
SELECT TO_CHAR(H.DT_ENTRADA,'MM') AS "MES", E.NM_ESTADO AS "ESTADO", COUNT(H.CD_HOSPEDAGEM) AS "TOTAL DE HOSPEDAGENS"
FROM T_AM_SCN_PESSOA P
JOIN T_AM_SCN_HOSPEDAGEM H ON H.CD_CLIENTE = P.CD_PESSOA
JOIN T_AM_SCN_PESSOA_ENDE PE ON PE.CD_PESSOA = P.CD_PESSOA 
JOIN T_AM_SCN_LOGRADOURO L ON L.NR_CEP = PE.NR_CEP
JOIN T_AM_SCN_BAIRRO B ON B.CD_BAIRRO = L.CD_BAIRRO
JOIN T_AM_SCN_CIDADE C ON C.CD_CIDADE = B.CD_CIDADE
JOIN T_AM_SCN_ESTADO E ON E.CD_ESTADO = C.CD_ESTADO 
GROUP BY TO_CHAR(H.DT_ENTRADA,'MM'), E.NM_ESTADO
ORDER BY TO_CHAR(H.DT_ENTRADA,'MM');

-- QUESTAO 9 --
SELECT TP.DS_TIPO_QUARTO, COUNT(*)
FROM T_AM_SCN_TIPO_QUARTO TP
JOIN T_AM_SCN_QUARTO Q ON Q.CD_TIPO_QUARTO = TP.CD_TIPO_QUARTO
JOIN T_AM_SCN_RESERVA_QUARTO RQ ON RQ.NR_QUARTO = Q.NR_QUARTO
JOIN T_AM_SCN_HOSPEDAGEM H ON H.CD_RESERVA = RQ.CD_RESERVA
GROUP BY TP.DS_TIPO_QUARTO
ORDER BY TP.DS_TIPO_QUARTO ASC;

--QUESTAO 10 --
SELECT PS.CD_TIPO_SERVICO, PS.DS_SERVICO
FROM T_AM_SCN_PRODUTO_SERVICO PS
LEFT JOIN T_AM_SCN_CONSUMO C ON C.CD_TIPO_SERVICO = PS.CD_TIPO_SERVICO
WHERE PS.NR_TIPO = 2 AND C.CD_TIPO_SERVICO IS NULL;

-- QUESTAO 11 --
SELECT P.NM_PESSOA, Q.NR_ANDAR, Q.NR_QUARTO
FROM T_AM_SCN_PESSOA P
JOIN T_AM_SCN_HOSPEDAGEM H ON H.CD_CLIENTE = P.CD_PESSOA
JOIN T_AM_SCN_QUARTO Q ON Q.NR_QUARTO = H.NR_QUARTO
WHERE P.NM_PESSOA LIKE '%ROSA%' AND Q.NR_ANDAR =2;

-- QUESTAO 12 --
SELECT P.CD_PESSOA, P.NM_PESSOA, F.DT_ADMISSAO
FROM T_AM_SCN_FUNCIONARIO F
JOIN T_AM_SCN_PESSOA P ON P.CD_PESSOA = F.CD_FUNCIONARIO
WHERE F.DT_ADMISSAO <= ADD_MONTHS(TRUNC(SYSDATE), -12*5);

-- QUESTAO 13 -- 
SELECT C.CD_CLIENTE, P.NM_PESSOA, C.DT_NASCIMENTO, C.DS_EMAIL
FROM T_AM_SCN_PESSOA P
JOIN T_AM_SCN_CLIENTE C ON C.CD_CLIENTE = P.CD_PESSOA
WHERE C.DT_NASCIMENTO = TRUNC(SYSDATE + 1);

-- QUESTAO 14 --
UPDATE T_AM_SCN_HIST_PRECO HP 
SET HP.VL_PRECO = HP.VL_PRECO * 1.15
WHERE HP.DT_VALIDADE = (SELECT MAX(DT_VALIDADE) FROM T_AM_SCN_HIST_PRECO


-- QUESTAO 15 --
UPDATE T_AM_SCN_QUARTO Q JOIN ON
T_AM_SCN_TIPO_QUARTO TP WHERE

UPDATE T_AM_SCN_PRODUTO_SERVICO SET VALOR = VALOR+(VALOR*(15/100))

SELECT P.NM_PESSOA, RQ.NR_QUARTO, Q.NR_ANDAR
FROM T_AM_SCN_PESSOA P
JOIN T_AM_SCN_HOSPEDAGEM H ON H.CD_CLIENTE = P.CD_PESSOA
JOIN T_AM_SCN_RESERVA_QUARTO RQ ON RQ.NR_QUARTO = H.NR_QUARTO
JOIN T_AM_SCN_QUARTO Q ON Q.NR_QUARTO = RQ.NR_QUARTO
JOIN T_AM_SCN_TIPO_QUARTO TP ON TP.CD_TIPO_QUARTO = Q.CD_TIPO_QUARTO
WHERE P.NM_PESSOA LIKE '%ROSA%';


SELECT * FROM T_AM_SCN_FUNCIONARIO;
SELECT * FROM T_AM_SCN_HOSPEDAGEM;
SELECT * FROM T_AM_SCN_PESSOA;
SELECT * FROM T_AM_SCN_CLIENTE;
SELECT * FROM T_AM_SCN_HIST_PRECO;
SELECT * FROM T_AM_SCN_HIST_VALOR;
SELECT * FROM T_AM_SCN_TIPO_QUARTO;
SELECT * FROM T_AM_SCN_QUARTO;
SELECT * FROM T_AM_SCN_CONSUMO;
SELECT * FROM T_AM_SCN_PRODUTO_SERVICO;
SELECT * FROM T_AM_SCN_HIST_PRECO;

SELECT DT_INICIO_RESERVA, DT_FINAL_RESERVA FROM T_AM_SCN_RESERVA 
WHERE DT_INICIO_RESERVA >= '01/09/15' AND DT_FINAL_RESERVA <= '05/10/15';

SELECT * FROM T_AM_SCN_RESERVA;